<!DOCTYPE html>
<html lang="pl">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <?php require './views/partial/style.phtml' ?>
  <title>Main</title>
  <?php
    require './php/index-code.php';
    require './php/my-sql-n.php';
    $mysql = new MySqlN();
    $indexCode = new IndexCode(
      $mysql->getCategories(),
      $mysql->getQBarQ(20)
    );
  ?>
</head>
<body>
  <?php require './views/partial/header.phtml' ?>
  <main>
    <?php require './views/partial/search-bar.phtml' ?>
    <?= "ToDo: Prosty formularz do dodawania" ?>
  </main>
</body>
</html>