<!DOCTYPE html>
<html lang="pl">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="./src/style/style.css" />
  <title>O Nas</title>
  <?php
    require './src/php/index-code.php';
    require './src/php/my-sql-n.php';
    $mysql = new MySqlN();
    $indexCode = new IndexCode(
      $mysql->getCategories()
    );
  ?>
</head>
<body>
  <?php require './src/views/partial/header.phtml' ?>
  <main>
    <div class="author">
      <p>Twórca projektu: Filip Skoczeń</p>
    </div>
    <div class="code">
      <a href="https://github.com/Untlsn/q-base.git" target="_blank">Kod źródłowy</a>
    </div>
  </main>
</body>
</html>