<!DOCTYPE html>
<html lang="pl">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="./src/style/style.css" />
  <title>Nowe</title>
  <?php
    require './src/php/index-code.php';
    require './src/php/my-sql-n.php';
    $mysql = new MySqlN();
    $indexCode = new IndexCode(
      $mysql->getCategories(),
      $mysql->getNewQBarQ(20)
    );
  ?>
</head>
<body>
  <?php require './src/views/partial/base.phtml' ?>
</body>
</html>