<header class="header">
  <a href="/" class="header__logo" style="background-image: url(./src/img/logo.png);"></a>
  <nav class="header__nav">
    <a href="/popular" class="header__nav-option">popularne</a>
    <div class="header__nav-option header__nav-option--category">kategorie</div>
    <div class="category-box">
      <?php $indexCode->createCategory(null) ?>
    </div>
    <a href="/new" class="header__nav-option">nowe</a>
    <a href="/by-me" class="header__nav-option">o nas</a>
  </nav>
  <div class="header__buttons-wrapper">
    <div class="header__button header__button--search" style="color: gray;">
      <i class="fas fa-search"></i>
      <span>szukaj</span>
    </div>
    <div class="header__button header__button--login">zaloguj</div>
    <a href="/add" class="header__button header__button--add">dodaj</a>
  </div>
</header>
<div class="header__space"></div>

