<form action="./search" class="search-bar">
  <input type="text" placeholder="Szukaj Q">
  <input type="submit" value="SZUKAJ">
  <div class="exit">X</div>
</form>
<script>
  const searchBar = document.querySelector('.search-bar')
  document.querySelector('.header__button--search').addEventListener('click', () => {
    searchBar.classList.add('search-bar-visible')
  })
  document.querySelector('.exit').addEventListener('click', () => {
    searchBar.classList.remove('search-bar-visible')
  })
</script>
